server:
  port: 8888
  
spring:
  application:
    name: myvalue
  cloud:
    config:
      server:
        git:
         uri: https://github.com/Jose-Fernandez-Vallejo/microserviceconfigServer/microserviceConfigServer
         default-label: main
         search-paths:
          - '*-service'