server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
         uri: https://github.com/Jose-Fernandez-Vallejo/microserviceconfigServer.git
         default-label: main
         search-paths:
          - '*service'